#!/usr/bin/env bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH


##############################################################################
# User specific aliases and functions
##############################################################################
# Paths
export PATH="$HOME/Sync/bin/:$PATH"

# For adding extra info files
export INFOPATH=/home/ape/Programming/info/Python-3.12.1/Doc/build/texinfo/:${INFOPATH}

# Commented out : setting TERM can add nonsense characters to emacs terms
# export TERM=xterm-256color
export HISTFILESIZE=10000

# Display hiden files first with dired
export LC_COLLATE="C"

################# PATH #####
export PATH="~/repos/emacs/src":$PATH  # am I adding to much to namespace?
export PATH="~/.cargo/bin":$PATH  # texlab

############# aliases ##########################
# User specific aliases and functions
alias ema='setsid emacs'
alias em='emacs -nw'
alias e='emacs -nw -q'
alias open='gnome-open'
alias okular='setsid okular'

# # quicker ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

#sizing
alias sizeDirs='du -hs ./* | sort -rh | head -n 40'
alias sizeDirs_sub='du -hS ./* | sort -rh | head -n 40'
alias rmTrash='rm -rf ~/.local/share/Trash/*'

# ruff linting (pip install ruff)
alias rcheck='ruff check --fix -n'
alias rformat='ruff format -n'

#renames
alias docker='podman'


PS1='\e[1;36m\u\e[0m@\e[1;33m\h\e[0m:\e[1;31m\w\e[0m\n : '

#python path (path projects)
export PYTHONPATH="/home/ape/Sync/Programming/projects/radar/radar-signal-processing/":$PYTHONPATH

################ things to remember (never uncomment!) ###############
#activate openMPI (only aware of modules in Fedora)
# module load  mpi/mpich-x86_64

##running mx3d template
#/usr/bin/mpiexec -np 8 ./mx3d ./parameters.input -pg 8 1 1

################################## END USER DEFINED ###########################

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc

# # >>> conda initialize >>>
# # !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/usr/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/usr/etc/profile.d/conda.sh" ]; then
#         . "/usr/etc/profile.d/conda.sh"
#     else
#         export PATH="/usr/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# # <<< conda initialize <<<

### PYENV
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
