#+title: Syncing and Backup

Syncthing is to used to sync between devices, and =rsnapshot= is used to create a backup on my desktop.

* Structure
The overall structure is that each client device has a =~/Sync= directory. At home, my desktop (server) has a bind mounted =~/Sync=  from another drive due to the boot drive being too small:
#+begin_src shell
sudo mount --bind /mnt/ss1tb/Sync/ /home/ape/Sync
#+end_src
- Use =mount --bind= rather than symlink so GNU =stow= works correctly, a cleaner appearance is just a effective.
- Note to remove mount, do not delete (=rm=) use:  =sudo umount /home/ape/Sync=

* Syncthing
We use Sync thing to sync each client device's =~/Sync= to the home server's =~/Sync=
- I do not connect between client devices at all
** Install
#+begin_src shell
sudo dnf install syncthing
#+end_src

** Configure
#+begin_src shell :results silent
  firefox http://127.0.0.1:8384/
#+end_src

*** For speedup, uncheck "Relay's Enabled"
Found by clicking Actions in the upper right, Actions, Advanced, Options.

** Autostart
Can either:
1) ad =syncthing-start.desktop= from Syncthing's github to =~/.config/autostart=.
2) just add to startup applications via =Tweaks=. Both  do the _SAME_ thing-- do this!

* rsnapshot

** configuration:
https://docs.rockylinux.org/guides/backup/rsnapshot_backup/
https://wiki.archlinux.org/title/Rsnapshot

*** Timers
source: https://gist.github.com/etskinner/a6d109838f3674360b5c73e6bbd9ca3b
#+begin_src shell :tangle /etc/systemd/system/rsnapshot@.service
  [Unit]
  Description=rsnapshot (%I) backup

  [Service]
  Type=oneshot
  Nice=19
  IOSchedulingClass=idle
  ExecStart=/usr/bin/rsnapshot %I
#+end_src

#+begin_src shell :tangle /etc/systemd/system/rsnapshot-hourly.timer
  [Unit]
  Description=rsnapshot hourly backup

  [Timer]
  OnCalendar=hourly
  Persistent=true
  Unit=rsnapshot@hourly.service

  [Install]
  WantedBy=timers.target
#+end_src

#+begin_src shell :tangle /etc/systemd/system/rsnapshot-daily.timer
  [Unit]
  Description=rsnapshot daily backup

  [Timer]
  OnCalendar=23:40
  Persistent=true
  Unit=rsnapshot@daily.service

  [Install]
  WantedBy=timers.target
#+end_src

#+begin_src shell :tangle /etc/systemd/system/rsnapshot-weekly.timer
  [Unit]
  Description=rsnapshot weekly backup

  [Timer]
  OnCalendar=Sun, 23:20
  Persistent=true
  Unit=rsnapshot@weekly.service

  [Install]
  WantedBy=timers.target
#+end_src

#+begin_src shell :tangle /etc/systemd/system/rsnapshot-monthly.timer
  [Unit]
  Description=rsnapshot monthly backup

  [Timer]
  OnCalendar=Sun *-*-1,2,3,4,5,6,7 23:00
  Persistent=true
  Unit=rsnapshot@monthly.service

  [Install]
  WantedBy=timers.target
#+end_src

*** Enable and start
Example, do for each timer:
#+begin_src shell
systemctl enable rsnapshot-hourly.timer
systemctl start rsnapshot-hourly.timer
#+end_src


** Restore old state
Use =rsync= (or =cp=), example:
#+begin_src shell
rsync -avc --delete /mnt/wd4tb/backups/hourly.1/localhost/mnt/ss1tb/Sync /mnt/ss1tb/
#+end_src

* rsync general example
#+begin_src shell
  rsync -avc --delete
  --exclude 'Dropbox/.dotfiles/.emacs.d/eln-cache'
  --exclude '#*'
  /mnt/ss1tb/Dropbox  /mnt/wd4tb/
#+end_src

